Add Event::as_raw_event
tokio-rs/mio pull request #1430
Opened 2021-01-05 13:50 UTC by Thomasdezeeuw

Returns the OS specific event.

Closes #990.

2021-01-05 14:11 UTC, Darksonn approved these changes

2021-01-05 15:54 UTC, Thomasdezeeuw commented
I'm wondering if this doesn't need some scarier docs? It's *very* OS specific and currently only available on Unix.

2021-01-05 23:12 UTC, djarek commented on src/event/event.rs
> +    /// programs should not depends on this function and should only use the
```suggestion
    /// programs should not depend on this function and should only use the
```
Typo

2021-01-06 18:28 UTC, carllerche commented
If we do this, we should make *very* sure `sys::Event` is a type defined in `mio` itself and not re-exporting a `libc` or `winapi` type.

2021-01-06 18:43 UTC, Thomasdezeeuw commented
> If we do this, we should make _very_ sure `sys::Event` is a type defined in `mio` itself and not re-exporting a `libc` or `winapi` type.

But this literally returns `kevent`/`epoll_event` that is the whole point of this method. I mean to use to e.g. to determine the amount of bytes available for reading. For `kqueue(2)` this is stored in `kevent.data` with the `EVFILT_READ` flag.

2021-01-06 19:06 UTC, carllerche commented
We can return a struct defined by `mio` w/ `#[repr(C)]` and a layout that matches the event struct. By exporting a struct defined in a separate crate, we would bind the public mio API to that crate. Should `libc` release v0.3, we would not be able to update. We made this mistake w/ Mio 0.6 & winapi.

2021-01-06 19:07 UTC, carllerche commented
Personally, if the goal is to expose platform specific data, I would define platform specific accessor fns on `Event` to get that data.

2021-01-06 19:08 UTC, carllerche requested changes
IMO we should not expose the platform struct and instead provide platform specific accessors.

2021-01-06 19:08 UTC, carllerche commented on src/event/event.rs
> +    pub fn as_raw_event(&self) -> &sys::Event {
This binds the mio public API to a libc version. If the goal is to provide access to platform specific data, we can define accessors on the current `Event` struct.

2021-01-08 13:04 UTC, Thomasdezeeuw commented
@carllerche you're right about binding to a specific libc version, didn't really think about that.

Maybe it's better to provide additional methods instead, e.g. `bytes_readable(&self) -> Option<usize>` or something. A possible problem with that is however that we'll have a bunch of API that might only work on a single platform. For example `kqueue` supports signals, however `epoll` and `IOCP` don't, so than we get API that only works on kqueue. I'll think about it a bit more, but I'll close this for now.

2021-01-08 13:04 UTC, closed without merging