Use epoll_create() as a fallback for epoll_create1()
tokio-rs/mio pull request #1590
Opened 2022-07-02 23:11 UTC by link2xt

Fixes #1473

2022-07-03 09:40 UTC, Thomasdezeeuw requested changes
@link2xt as I've said it can't impact the performance of existing code, which this does. This will not be accepted as is.

2022-07-03 09:49 UTC, Thomasdezeeuw commented
> @Thomasdezeeuw How does this impact the performance? Is epoll_create such a frequent operation that not calling fcntl saves any cycles? The crate doesn't have any benchmark, how do you measure it?

I'm not willing to revert to `epoll_create` on all platforms, I've stated this before.

2022-07-03 10:19 UTC, Thomasdezeeuw commented
> Threre is zero difference in syscall implementation, both call `do_epoll_create`. `epoll_create1` is not faster than `epoll_create`: https://elixir.bootlin.com/linux/v5.19-rc4/source/fs/eventpoll.c#L2010
> 
> The only difference is that there is an additional `fcntl` syscall to set a flag once at the beginning of event loop.

Can I just say that this is becoming really tiring...

They reason that `epoll_create1` was introduced is the same reason we use it. We don't control the entire program, so it's possible to `fork` between `epoll_create` and the next call to `fcntl`, causing the file descriptor to be leaked. We don't want this so we use `epoll_create1`.

2022-07-03 15:29 UTC, notgull commented
Is there any particular reason we can't use what the `polling` crate does for [`epoll`](https://github.com/smol-rs/polling/blob/989c515fa2ebaafecb0df933dd6a081c3571f0ec/src/epoll.rs#L28), where it tries to use a syscall to call `epoll_create1`, and if that fails with `ENOSYS`, it falls back onto the `epoll_create` implementation? That would be the best of both worlds.

2022-07-03 17:54 UTC, Noah-Kennedy commented
I think that would be fair to do. It shouldn't degrade performance or worsen anything for system which support the newer API, and would provide support for the older systems.

2022-07-04 09:47 UTC, Thomasdezeeuw commented
That should fine with the addition of some documentation that we fall back to a racy version using `epoll_create`.

2022-07-09 14:26 UTC, notgull commented
Hmm, I don't think this works. I think you need to use the `libc::syscall` function to call `epoll_create1`. Otherwise, it'll try to link to the `epoll_create1` function in `libc`, which may not exist.

2022-07-09 15:48 UTC, Thomasdezeeuw requested changes
This is going into the right direction. However we're not going to use raw system calls. Also please add the the documentation to `Poll::new` to I asked for regarding the possible data race.

2022-07-09 15:48 UTC, Thomasdezeeuw commented on src/sys/unix/selector/epoll.rs
> +        let ep = syscall!(syscall(libc::SYS_epoll_create1, flag))
We're not going to use raw system calls. Please add the `epoll_create1` function the libc crate instead.

2022-07-10 11:54 UTC, Thomasdezeeuw commented on src/sys/unix/selector/epoll.rs
> +        let ep = syscall!(syscall(libc::SYS_epoll_create1, flag))
> Is there any problem with using a raw system call?

It makes maintenance harder.

But I guess we can make an exception here, could you extract the system call stuff to a new `epoll_create1` function, that for platforms that support it call `libc::epoll_create1` and for others use the raw system interface?

2022-07-11 09:10 UTC, Thomasdezeeuw reviewed
Almost their I think, I'm still not super happy about using raw system calls, but if we can minimise the usage to just Android I think it would be acceptable.

2022-07-11 09:10 UTC, Thomasdezeeuw commented on src/sys/unix/selector/epoll.rs
> +    #[cfg(not(any(target_os = "illumos", target_os = "redox")))]
Could you change this to be android only with a comment referring to https://github.com/tokio-rs/mio/issues/1473 and explaining that Android API level 16 doesn't define `epoll_create1`. I really like to minimise the use of raw system calls.

2022-07-17 19:42 UTC, Thomasdezeeuw approved these changes

2022-07-17 19:43 UTC, Thomasdezeeuw commented
I'm going to merge this as and will do a little cleanup and more docs into another pr.

2022-07-17 19:44 UTC, merged