Add AIX operating system support
tokio-rs/mio pull request #1704
Opened 2023-08-01 08:40 UTC by ecnelises

AIX does not have `epoll` or `kqueue` functionality, so it relies on `force_poll_poll` feature.

2023-08-01 08:51 UTC, Thomasdezeeuw requested changes

2023-08-01 08:51 UTC, Thomasdezeeuw commented on src/sys/unix/waker.rs
> +            syscall!(pipe(fds.as_mut_ptr()))?;
You still need to set the `libc::O_NONBLOCK | libc::O_CLOEXEC` otherwise this will not work.

2023-08-03 10:33 UTC, Thomasdezeeuw commented on src/sys/unix/waker.rs
> +        fn pipe2() -> io::Result<(RawFd, RawFd)> {
Since this is essentially the same code as in `src/sys/unix/pipe.rs`, maybe we should reuse that code.

2023-08-08 08:21 UTC, Thomasdezeeuw approved these changes

2023-08-09 02:45 UTC, ecnelises commented
`cargo check --target x86_64-unknown-illumos --no-default-features --features os-poll` fails because no `os-ext` feature specified, and `crate::unix::pipe::new` relies on `os-ext`. Should we guard `mod pipe` with `os-ext`?

2023-08-09 14:16 UTC, Thomasdezeeuw commented
@ecnelises I've opened https://github.com/ecnelises/mio/pull/1 to solve that.

2023-08-21 15:57 UTC, merged

2023-08-21 15:57 UTC, Thomasdezeeuw commented
Thanks @ecnelises